ServerEvents.recipes(event => {
    event.remove('forcecraft:infuser/convert_time_torch')
    event.remove('ae2:network/blocks/spatial_anchor')
    event.remove('easy_villagers:auto_trader')
    event.remove('easy_villagers:iron_farm')
    event.remove('reliquary:alkahestry_tome')
    event.remove('energizedpower:crafting/time_controller')
    event.remove('energizedpower:crafting/weather_controller')
    event.remove('extradisks:disk/shaped/infinite_storage_disk')
    event.remove('extradisks:blocks/infinite_storage_block')
    event.remove('extradisks:part/infinite_storage_part')
    event.remove('extradisks:disk/shaped/infinite_fluid_storage_disk')
    event.remove('extradisks:part/infinite_fluid_storage_part')
    event.remove('extradisks:blocks/infinite_fluid_storage_block')
})