/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
MMREvents.machines(catalyst => {
    /**
     * Creates a machine with the given ResourceLocation (namespace:machine) equivalent to the json -> datapackNamespace:jsonName
     */
    catalyst.create("mmr:personal_beacon")
        /**
         * Applies the color to the machine with the format:
         * #AlphaAlphaRedRedGreenGreenBlueBlue
         * color in int number format
         */
        .color('#ffB57EDC')
        /**
         * The name that the machine should display in the controller item and in the controller GUI -> default localized with the id of the creation
         */
        .name(Component.translatable("catalyst.mmr.machine.personal_beacon"))
        /**
         * The multiblock definition
         */
       .structure(
            MMRStructureBuilder.create()
            .pattern([
                [
                    "abBCCCxbbbbwCCCtbbbbBCCCxba",
                    "bBAiiiyxBCCviiiuCCxBAiiiyxb",
                    "wviaiaiyAnnioooinnyAiaiaiut",
                    "riaqqqainniooiooinniaqqqaip",
                    "riiqqqiiniooisiooiniiqqqiip",
                    "riaqqqainiooisiooiniaqqqaip",
                    "gliaiaiinnioisioinniiaiaikf",
                    "bgliiiisiniooiooinisiiiikfb",
                    "bwvnnnnisinioooinisinnnnutb",
                    "brnniinniinioooiniinniinnpb",
                    "brniooiinnnnioinnnniiooinpb",
                    "BAioooooiinnioinniioooooiyx",
                    "riooiiioooiiqqqiioooiiiooip",
                    "rioisssiooooqqqooooisssioip",
                    "riooiiioooiiqqqiioooiiiooip",
                    "ejioooooiinnioinniioooooihc",
                    "brniooiinnnnioinnnniiooinpb",
                    "brnniinniinioooiniinniinnpb",
                    "bglnnnnisinioooinisinnnnkfb",
                    "bwviiiisiniooiooinisiiiiutb",
                    "wviaiaiinnioisioinniiaiaiut",
                    "riaqqqainiooisiooiniaqqqaip",
                    "riiqqqiiniooisiooiniiqqqiip",
                    "riaqqqainniooiooinniaqqqaip",
                    "gliaiaihjnnioooinnhjiaiaikf",
                    "bejiiihceddliiikddcejiiihfb",
                    "abedddcbbbbgdddfbbbbedddcba"
                ],
                [
                    "D                         D",
                    "                           ",
                    "                           ",
                    "   bCb    D     D    bCb   ",
                    "   rFp               rFp   ",
                    "   bdb               bdb   ",
                    "                           ",
                    "                           ",
                    "           D   D           ",
                    "                           ",
                    "   D                   D   ",
                    "        D         D        ",
                    "            bCb            ",
                    "            rFp            ",
                    "            bdb            ",
                    "        D         D        ",
                    "   D                   D   ",
                    "                           ",
                    "           D   D           ",
                    "                           ",
                    "                           ",
                    "   bCb               bCb   ",
                    "   rFp               rFp   ",
                    "   bdb    D     D    bdb   ",
                    "                           ",
                    "                           ",
                    "D                         D"
                ],
                [
                    "G                         G",
                    "                           ",
                    "                           ",
                    "          G     G          ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "           G   G           ",
                    "                           ",
                    "   G                   G   ",
                    "        G         G        ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "        G         G        ",
                    "   G                   G   ",
                    "                           ",
                    "           G   G           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "          G     G          ",
                    "                           ",
                    "                           ",
                    "G                         G"
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    H                 H    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    H                 H    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    I                 I    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    I                 I    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "    M                 M    ",
                    "                           ",
                    "    I                 I    ",
                    " L IsI K           L IsI K ",
                    "    I                 I    ",
                    "                           ",
                    "    J                 J    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    M                 M    ",
                    "                           ",
                    "    I                 I    ",
                    " L IsI K           L IsI K ",
                    "    I                 I    ",
                    "                           ",
                    "    J                 J    ",
                    "                           "
                ],
                [
                    "                           ",
                    "    i                 i    ",
                    "                           ",
                    "    I                 I    ",
                    " i INI i           i INI i ",
                    "    I                 I    ",
                    "                           ",
                    "    i                 i    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    i                 i    ",
                    "                           ",
                    "    I                 I    ",
                    " i INI i           i INI i ",
                    "    I                 I    ",
                    "                           ",
                    "    i                 i    ",
                    "                           "
                ],
                [
                    "                           ",
                    "    C                 C    ",
                    "                           ",
                    "    I                 I    ",
                    " r IsI p           r IsI p ",
                    "    I                 I    ",
                    "                           ",
                    "    d                 d    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    C                 C    ",
                    "                           ",
                    "    I                 I    ",
                    " r IsI p           r IsI p ",
                    "    I                 I    ",
                    "                           ",
                    "    d                 d    ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    I                 I    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    I                 I    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    H                 H    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "             O             ",
                    "            OHO            ",
                    "             O             ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "    H                 H    ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "            MiM            ",
                    "           LisiK           ",
                    "           LisiK           ",
                    "       P   LisiK   P       ",
                    "      PsP   JiJ   PsP      ",
                    "       PsP       PsP       ",
                    "        P         P        ",
                    "                           ",
                    "    MMM             MMM    ",
                    "   LiiiK     O     LiiiK   ",
                    "   isssi    OIO    isssi   ",
                    "   LiiiK     O     LiiiK   ",
                    "    JJJ             JJJ    ",
                    "                           ",
                    "        P         P        ",
                    "       PsP       PsP       ",
                    "      PsP   MiM   PsP      ",
                    "       P   LisiK   P       ",
                    "           LisiK           ",
                    "           LisiK           ",
                    "            JiJ            ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "            imi            ",
                    "         iiiQiQiii         ",
                    "       iiQQQQiQQQQii       ",
                    "      iQQQQQQiQQQQQQi      ",
                    "     iQiQQQQiRiQQQQiQi     ",
                    "     iQQiQii   iiQiQQi     ",
                    "    iQQQQi       iQQQQi    ",
                    "    iQQQi         iQQQi    ",
                    "    iQQQi         iQQQi    ",
                    "   iQQQi    OIO    iQQQi   ",
                    "   iiiii    I I    iiiii   ",
                    "   iQQQi    OIO    iQQQi   ",
                    "    iQQQi         iQQQi    ",
                    "    iQQQi         iQQQi    ",
                    "    iQQQQi       iQQQQi    ",
                    "     iQQiQii   iiQiQQi     ",
                    "     iQiQQQQiiiQQQQiQi     ",
                    "      iQQQQQQiQQQQQQi      ",
                    "       iiQQQQiQQQQii       ",
                    "         iiiQiQiii         ",
                    "            iii            ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "             S             ",
                    "      D             D      ",
                    "       S     T     S       ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "            OIO            ",
                    "     S      INI      S     ",
                    "            OIO            ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "       S           S       ",
                    "      D             D      ",
                    "             S             ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "      N             N      ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "            OIO            ",
                    "            I I            ",
                    "            OIO            ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "      N             N      ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "             O             ",
                    "            OIO            ",
                    "             O             ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "             O             ",
                    "            OHO            ",
                    "             O             ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ],
                [
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           ",
                    "                           "
                ]
            ])       
            .keys({
                "a":["occultism:otherrock"],
                "b":["occultism:otherrock_slab[type=bottom]"],
                "c":["occultism:otherrock_stairs[facing=west+half=bottom+shape=outer_right]"],
                "d":["occultism:otherrock_stairs[facing=north+half=bottom+shape=straight]"],
                "e":["occultism:otherrock_stairs[facing=east+half=bottom+shape=outer_left]"],
                "f":["occultism:otherrock_stairs[facing=north+half=bottom+shape=outer_left]"],
                "g":["occultism:otherrock_stairs[facing=north+half=bottom+shape=outer_right]"],
                "h":["occultism:otherrock_stairs[facing=north+half=bottom+shape=inner_left]"],
                "i":[
                        "modular_machinery_reborn:casing_reinforced",
                        "#modular_machinery_reborn:inputbus",
                        "#modular_machinery_reborn:energyinputhatch",
                        "#modular_machinery_reborn_ars:sourceinputhatch"
                ],
                "j":["occultism:otherrock_stairs[facing=north+half=bottom+shape=inner_right]"],
                "k":["occultism:otherrock_stairs[facing=west+half=bottom+shape=inner_right]"],
                "l":["occultism:otherrock_stairs[facing=east+half=bottom+shape=inner_left]"],
                "n":['rechiseled:gold_block_bordered_connecting'],
                "o":["occultism:otherrock_slab[type=bottom]"],
                "p":["occultism:otherrock_stairs[facing=west+half=bottom+shape=straight]"],
                "q":["minecraft:netherite_block"],
                "r":["occultism:otherrock_stairs[facing=east+half=bottom+shape=straight]"],
                "s":['eternalores:source_block'],
                "t":["occultism:otherrock_stairs[facing=south+half=bottom+shape=outer_right]"],
                "u":["occultism:otherrock_stairs[facing=west+half=bottom+shape=inner_left]"],
                "v":["occultism:otherrock_stairs[facing=east+half=bottom+shape=inner_right]"],
                "w":["occultism:otherrock_stairs[facing=south+half=bottom+shape=outer_left]"],
                "x":["occultism:otherrock_stairs[facing=west+half=bottom+shape=outer_left]"],
                "y":["occultism:otherrock_stairs[facing=south+half=bottom+shape=inner_right]"],
                "A":["occultism:otherrock_stairs[facing=south+half=bottom+shape=inner_left]"],
                "B":["occultism:otherrock_stairs[facing=east+half=bottom+shape=outer_right]"],
                "C":["occultism:otherrock_stairs[facing=south+half=bottom+shape=straight]"],
                "D":["ars_additions:sourcestone_wall"],
                "F":["minecraft:beacon"],
                "G":["occultism:spirit_lantern"],
                "H":["minecraft:white_stained_glass"],
                "I":["minecraft:purple_stained_glass"],
                "J":["occultism:otherrock_stairs[facing=north+half=top+shape=straight]"],
                "K":["occultism:otherrock_stairs[facing=west+half=top+shape=straight]"],
                "L":["occultism:otherrock_stairs[facing=east+half=top+shape=straight]"],
                "M":["occultism:otherrock_stairs[facing=south+half=top+shape=straight]"],
                "N":["ars_nouveau:relay[waterlogged=false]"],
                "O":["occultism:iesnium_block"],
                "P":["occultism:otherrock_slab[type=top]"],
                "Q":["occultism:otherrock"],
                "R":["modular_machinery_reborn:casing_reinforced"],
                "S":['occultism:dark_iesnium_sacrificial_bowl'],
                "T":["ars_nouveau:storage_lectern[facing=north]"]
            })
        )
})