/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
MMREvents.machines(catalyst => {
    /**
     * Creates a machine with the given ResourceLocation (namespace:machine) equivalent to the json -> datapackNamespace:jsonName
     */
    catalyst.create("mmr:advanced_multismelter")
        .color('#FF5E0000')
        .name(Component.translatable("catalyst.mmr.machine.advanced_multismelter"))
        .structure(
        MMRStructureBuilder.create()
        .pattern([
        ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abiiibbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbffffffffgfffffffebbbbbba","abbbbbbdbbbbbbghgbbbbbbebbbbbba","abbbbbbdbffffffgfffffebebbbbbba","abbbbbbdbdbbbbbabbbbbebebbbbbba","abbbbbbdbdbbbbbabbbbbebebbbbbba","abbbbbbdbdccccccccccccbebbbbbba","abbbbbbdbbbbbbbabbbbbbbebbbbbba","abbbbbbdccccccccccccccccbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
        ["               a          xi   "," bbbbb                  ixxxi  "," b   b                  xixixx "," byyyb                  ixxiix "," byyyb                   xixxx "," byyyb        k k        x xx  "," bdbdb         w               ","  d d         w w         k k  ","  d d          w     vvv k   k ","  d dccvvv    k k    vvv       ","  d d  vvv blllllllb vvv k   k ","  d dccvvv tuuvvvuut      k k  ","           tuuvvvuut           ","           tuuvvvuut           ","       pbp bslqbqlsb           ","      pbbbp r bqb r k      k   ","       pbp    qbq              ","        p   k       k    k     ","                               ","                               ","               p               "," nnn   nnn    pbp        k k   "," nnn   nnn   pbbbp             "," nnn   nnn    pbp              ","               p               ","                  lll    k k   ","                 loool  k   k  "," nnn   nnn       loool         "," nnn   nnn       loool  k   k  "," nnn   nnn        lll    k k   ","                               "],
        ["               m               ","                         xix   "," k   k                   xxxx  ","                         xixxi ","                         ixix  ","              vvv              "," k   k       vvvvv             ","             vvvvv        k k  ","             vvvvv   BBB k   k ","     yyy      vvv    BBB       ","     yyy   blllllllb yBy k   k ","     yyy   tuuyyyuut      k k  ","           tuuyyyuut           ","           tuuyyyuut           ","           bllqbqllb           ","        k   r bqb r k      k   ","              qbq              ","            k       k    k     ","                               ","                               ","                               "," AAA   AAA               k k   "," AAA   AAA     k               "," AAA   AAA                     ","                               ","                  lll    k k   ","                 lo ol  k   k  "," AAA   AAA       loool         "," AAA   AAA       loo l  k   k  "," AAA   AAA        lll    k k   ","                               "],
        ["                               ","                               "," k   k                   xix   ","  CCC                    xiix  ","  CCC                     x i  ","  CCC         vvv              "," k   k       v   v             ","             v   v        k k  ","             v   v       k   k ","              vvv              ","           blllllllb     k   k ","           tuuuuuuut      k k  ","           tuuuuuuut           ","           tuuuuuuut           ","           bllqbqllb           ","        k   r bqb r k      k   ","              qbq              ","            k       k    k     ","                               ","                               ","                               "," AAA   AAA               k k   "," AAA   AAA     k               "," AAA   AAA                     ","                               ","                  lll    k k   ","                 l   l  k   k  "," AAA   AAA       loo l         "," AAA   AAA       l o l  k   k  "," AAA   AAA        lll    k k   ","                               "],
        ["                               ","                               "," k   k                         ","  bbb                          ","  bbb                          ","  bbb                          "," k   k                         ","                          b b  ","                         bbbbb ","                          b b  ","           bbbbbbbbb     bbbbb ","           blDlDlDlb      b b  ","           blDlDlDlb           ","           blDlDlDlb           ","           bbbqbqbbb           ","        k   r bqb rrrrrrrrrr   ","            r qbq          r   ","            rrrrrrrrrrrrrr r   ","                         r r   ","                         r r   ","                         r r   "," AAA   AAA               r r   "," AAA   AAA     k         r r   "," AAA   AAA               r r   ","                         r r   ","                  lll    k r   ","                 l   l  k  rk  "," AAA   AAA       l o l     r   "," AAA   AAA       l   l  k   k  "," AAA   AAA        lll    k k   ","                               "],
        ["                               ","                               "," k   k                         ","  E E                          ","                               ","  E E                          "," k   k                         ","                          k k  ","                         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                  bbb    bbb   ","                 bbbbb  bbbbb  ","                 bbbbb  bbbsb  ","                 bbbbb  bbbbb  ","                  bbb    bbb   ","                               "],
        ["                               ","                               "," bb bb                         "," bbbbb                         ","  bbb                          "," bbbbb                         "," bb bb                         ","                          k k  ","                         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                         lll   ","                        luuul  ","                        luFul  ","                        luuul  ","                         lll   ","                               "],
        ["                               ","                               ","                               ","                               ","                               ","                               ","                               ","                          k k  ","                         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                         lll   ","                        luuul  ","                        luFul  ","                        luuul  ","                         lll   ","                               "],
        ["                          HHH  ","                         HHHHH ","                         HHHHH ","                         HHHHH ","                          HHH  ","                               ","                               ","                          b b  ","                         bbbbb ","                          b    ","                         bbbbb ","                          b b  ","                               ","        G                      ","       GbG    qbq              ","      GbbbG   bqb              ","       GbG    qbq              ","        G                      ","                               ","                               ","               G               ","              GbG              ","             GbbbG             ","              GbG              ","               G         r     ","                         lll   ","                        luuul  ","                        luFul  ","                        luuul  ","                         lll   ","                               "],
        ["                          HHH  ","                         HxixH ","                         HxxxH ","                         HixiH ","                          HHH  ","                               ","                               ","                          k k  ","                         k   k ","        lq                     ","        llq              k   k ","       llqlq              k k  ","       llqll                   ","      llqll                    ","      llqll   qbq              ","      qqqqq   bqb              ","      llqll   qbq              ","      llqll                    ","       llqll                   ","       llqlql     lq           ","        llqllllqllllq          ","        lqlqqllqllqqlq         ","         llllqqqqqllll         ","           llllqllll           ","             llqll       r     ","                         lll   ","                        luuul  ","                        luFul  ","                        luuul  ","                         lll   ","                               "],
        ["                          H H  ","                           x   ","                          ixx  ","                           x   ","                          H H  ","                               ","                               ","                          k k  ","       lq                k   k ","       lot                     ","      lloot              k   k ","      loooot              k k  ","      loooooq                  ","     loooool                   "," H   loooool  qbq              "," HH  qoooooq  bqb              "," H   loooool  qbq              ","     loooool                   ","      loooooq     q            ","      loooooollqllot           ","      lloooooooooooot          ","       looooooooooooot         ","       lqoooooooooooooq        ","        lllooooooooolll        ","          lllooooolll    r     ","             llqll       bbb   ","                        bbbbb  ","                        bsbbb  ","               H        bbbbb  ","              HHH        bbb   ","                               "],
        ["                               ","                          H H  ","                           x   ","                          H H  ","                               ","                               ","                               ","       q                  k k  ","      q t                k   k ","      q  t                     ","     q    t              k   k ","     q     t              k k  ","     q      tlqqq              "," H  q       lqbqbq             ","    q   BB  qbbqbbq  vv        "," II q  BBB  qqqqqqq  vvv       ","    q   BB  qbbqbbq  vv        "," H  q       lqbqbq             ","     q       lqqqlt            ","     q             t           ","     q              t          ","      q       vvv    t         ","      q       vvv     t        ","       q       B       q       ","        qq           qq  r     ","          qqq     qqq    r     ","             qqqqq       r     ","                         r     ","               I               ","             H I H             ","                               "],
        ["                               ","                               ","                          HHH  ","                               ","                               ","                               ","                               ","       q                  b b  ","      l t     B B        bbbbb ","      l  t     B          b b  ","     l    t    B         bbbbb ","     l     t              b b  "," H   l      t                  ","    q   BB    bqb    vv        ","    l  BJJB  b   b  vxxv       ","    l BJJJB  q q q  vxxxv      ","    l  BJJB  b   b  vxxv       ","    q   BB    bqb    vv        "," H   l            t            ","     l             t           ","     l        vvv   t          ","      l      vxJJv   t         ","      l      vJxxv    t        ","       q      BxB      q       ","        ll     B     ll        ","          lll     lll          ","             qlllq             ","                               ","                               ","            H     H            ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t     B B        k   k ","      l  t    BJB              ","     l    t   BJB        k   k ","     l     t   B          k k  "," HH  q      t                  "," PP q   BB    ttt    vv        ","    l  BJJB  t   t  vxxv       "," LL N BJJJB  t q t  vxiiv      ","    l  BJJB  t   t  vixv       "," OO q   BB    ttt    vv        "," HH  q            t            ","     l             t           ","     l        vvv   t          ","      l      vJxiv   t         ","      l      BxJJB    t        ","       q      BiB      q       ","        ll     B     ll        ","          llq     qll          ","             qlNlq             ","                               ","            HM X KH            ","            HM X KH            ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t    B   B       k   k ","      l  t  HB   BH            ","     l    t HB   BH      k   k ","     l     t HBBBH        k k  "," H   l   HH t HHH   HH         ","    q   BB H  tHt  H vv        ","    l BB  B Ht H tH v  vv      ","    l     B HHHHHHH v          ","    l BB  B Ht H tH v  vv      ","    q   BB H  tHt  H vv        "," H   l   HH   HHH t HH         ","     l       H   H t           ","     l      H vvv H t          ","      l     Hv   vH  t         ","      l      v   v    t        ","       q      B B      q       ","        ll    B B    ll        ","          lll     lll          ","             qlllq             ","                               ","                               ","            H     H            ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t    B   B       k   k ","      l  t   B   B             ","     l    t  B   B       k   k ","     l     t  BBB         k k  ","     l      t                  "," H  q         ttt              ","    l        t   t             "," SS l        t   t             ","    l        t   t             "," H  q         ttt              ","     l            t            ","     l             t           ","     l              t          ","      l              t         ","      l               t        ","       q               q       ","        ll           ll        ","          lll     lll          ","             qlllq             ","                               ","               S               ","             H S H             ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","       q                  b b  ","      q t     BBB        bbbbb ","      q  t    BBB         bbb  ","     q    t   BBB        bbbbb ","     q     t              b b  ","     q      t qqq              ","    q        qbqbq             "," H  q       qbbqbbq            "," HH q       qqqqqqq            "," H  q       qbbqbbq            ","    q        qbqbq             ","     q        qqq t            ","     q             t           ","     q              t          ","      q              t         ","      q               t        ","       q               q       ","        qq           qq        ","          qqq     qqq          ","             qqqqq             ","                               ","               H               ","              HHH              ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","                          HHH  ","       lq                HHHHH ","       l t               HHHHH ","      ll  t              HHHHH ","      l    t              HHH  ","      l     q                  ","     l     ll                  ","     l     l                   ","     q     q              xxx  ","     l     l              xxx  ","     l     ll                  ","      l     ql   lq            ","      l      llqll t           ","      ll            t          ","       l             t         ","       lq             q        ","        lll         lll        ","          lll     lll          ","             llqll             ","                               ","                               ","                               ","                               ","                               "],
        ["                               ","                               ","                          R R  ","                               ","                               ","                               ","                               ","                               ","                         HTHTH ","        lq                     ","        llq              HTHTH ","       llqlq                   ","       llqll                   ","      llqll                    ","      llqll                    ","      qqqqq               bbb  ","      llqll               xxx  ","      llqll               xxx  ","       llqll                   ","       llqlql     lq           ","        llqllllqllllq          ","        lqlqqllqllqqlq         ","         llllqqqqqllll         ","           llllqllll           ","             llqll             ","                               ","                               ","                               ","                               ","                               ","                               "],
        ["                               ","                               ","                          bbb  ","                          V V  ","                          V V  ","                          V V  ","                          V V  ","                          V V  ","                         HWHWH ","                          V V  ","                         HWHWH ","                          V V  ","                          V V  ","                          V V  ","                          U U  ","                          bbb  ","                          xxx  ","                          xxx  ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               "],
        ["                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                          HHH  ","                               ","                          HHH  ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               "]
        ])
        .keys({
        "a":[
        "modular_machinery_reborn:casing_reinforced",
        '#modular_machinery_reborn:itembus',
        '#modular_machinery_reborn:energyhatch'],
        "b":"create_new_age:reactor_casing",
        "c":"mob_grinding_utils:entity_conveyor",
        "d":"mob_grinding_utils:entity_conveyor",
        "e":"mob_grinding_utils:entity_conveyor",
        "f":"mob_grinding_utils:entity_conveyor",
        "g":"minecraft:piston[extended=true+facing=up]",
        "h":"minecraft:redstone_block",
        "i":"minecraft:coal_block",
        "k":"create:metal_girder",
        "l":"create_new_age:reactor_glass",
        "n":"mekanism:induction_casing",
        "o":"create_new_age:solid_corium",
        "p":"minecraft:polished_blackstone_brick_slab[type=bottom]",
        "q":"mekanismgenerators:fusion_reactor_frame",
        "r":"immersiveengineering:fluid_pipe",
        "s":"minecraft:netherite_block",
        "t":"glassential:glass_ethereal",
        "u":["minecraft:water","minecraft:ice"],
        "v":"minecraft:netherite_block",
        "w":"minecraft:piston_head",
        "x":"minecraft:iron_block",
        "y":"eternalores:steel_block",
        "A":"mekanism:ultimate_induction_cell",
        "B":"eternalores:nethersteel_block",
        "C":"immersiveengineering:chute_iron",
        "D":"modular_machinery_reborn:casing_vent",
        "E":"minecraft:sticky_piston",
        "F":"minecraft:blue_ice",
        "G":"minecraft:polished_blackstone_brick_slab[type=top]",
        "H":"modular_machinery_reborn:casing_plain",
        "I":"mekanism:laser",
        "J":"minecraft:lava",
        "K":"mekanism:laser",
        "X":"mekanism:laser_amplifier",
        "L":"mekanism:laser_amplifier",
        "M":"mekanism:laser",
        "N":"mekanismgenerators:laser_focus_matrix",
        "O":"mekanism:laser",
        "P":"mekanism:laser",
        "R":"minecraft:chain[axis=y]",
        "S":"mekanism:laser",
        "T":"minecraft:grindstone",
        "U":"minecraft:polished_blackstone_wall",
        "V":"minecraft:polished_blackstone_wall",
        "W":"minecraft:polished_blackstone_wall"
        }))
});
/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/