//design by BitGardener https://www.youtube.com/watch?v=rXV_b7J1TB4
MMREvents.machines(catalyst => {
    /**
     * Creates a machine with the given ResourceLocation (namespace:machine) equivalent to the json -> datapackNamespace:jsonName
     */
    catalyst.create("mmr:fisher")
        /**
         * Applies the color to the machine with the format:
         * #AlphaAlphaRedRedGreenGreenBlueBlue
         * color in int number format
         */
        .color('#ff2a24bf')
        /**
         * The name that the machine should display in the controller item and in the controller GUI -> default localized with the id of the creation
         */
        .name(Component.translatable("catalyst.mmr.machine.fisher"))
        /**
         * The multiblock definition
         */
        .structure(
        MMRStructureBuilder.create()
        .pattern([
        ["             bcccccb             ","           cbcccccccbc           ","        cbbccdddddddccbbc        ","      cbccdddeeeeeeedddccbc      ","     cccddeeeeeeeeeeeeeddccc     ","    ccddeeeeeeeeeeeeeeeeeddcc    ","   ccdeeeeeeeeeeeeeeeeeeeeedcc   ","   bcdeeeeeeeeeeeeeeeeeeeeedcb   ","  ccdeeeeeeeeeeeeeeeeeeeeeeedcc  ","  bcdeeeeeeeeeeeeeeeeeeeeeeedcb  ","  bdeeeeeeeeeeeeeeeeeeeeeeeeedb  "," ccdeeeeeeeeeeeeeeeeeeeeeeeeedcc "," bcdeeeeeeeeeeeeeeeeeeeeeeeeedcb ","bcdeeeeeeeeeeeeeeeeeeeeeeeeeeedcb","ccdeeeeeeeeeeeeeeeeeeeeeeeeeeedcc","ccdeeeeeeeeeeeeeeeeeeeeeeeeeeedcb","ccdeeeeeeeeeeeeeeeeeeeeeeeeeeedcc","ccdeeeeeeeeeeeeeeeeeeeeeeeeeeedcb","ccdeeeeeeeeeeeeeeeeeeeeeeeeeeedcc","bcdeeeeeeeeeeeeeeeeeeeeeeeeeeedcb"," bcdeeeeeeeeeeeeeeeeeeeeeeeeedcb "," ccdeeeeeeeeeeeeeeeeeeeeeeeeedcc ","  bdeeeeeeeeeeeeeeeeeeeeeeeeedb  ","  bcdeeeeeeeeeeeeeeeeeeeeeeedcb  ","  ccdeeeeeeeeeeeeeeeeeeeeeeedcc  ","   bcdeeeeeeeeeeeeeeeeeeeeedcb   ","   ccdeeeeeeeeeeeeeeeeeeeeedcc   ","    ccddeeeeeeeeeeeeeeeeeddcc    ","     cccddeeeeeeeeeeeeeddccc     ","      cbccdddeeeeeeedddccbc      ","        cbbccdddddddccbbc        ","           cbcccccccbc           ","             bcccccb             "],
        ["              b b b              ","           b  f f f  b           ","        b  f ddddddd f  b        ","      b f dddiikkkkkddd f b      ","     bf ddkkiiikkkkkkkkdd fb     ","    b ddggkkiiikkkkkkeekkdd b    ","   bfdggggkkkikkkkkiieeeiiidfb   ","     dggggeikkkkkkkiikekkiid     ","  bfdggggeeekkkkkkkkkkkkkkgidfb  ","    dgggkeeekkkkkkkkkkkkkkggd    ","   dggkkkeeikkiikkkkkkkkkkgggd   "," bfdikkkkkekkkkiikkkkkkkkggggdfb ","   dikkkkkikkkkikkkkkkgggggggd   ","  diiikkkiikkkkkkkkkkgggggggggd  ","bfdgigkkkkkikkkkkkkkggggggggggdfb","  dggggkkkkkkkkkkkkkkkggggggggd  ","bfdgggkkkkgggkkkkkkkkkkkgggggidfb","  dgggkkkgggggkkkkkkkkjkkkggiid  ","bfdgggkkkggggggkkkkkkjeekkkkiidfb","  diikkkkkggggkkkkkkkeeejkkkiid  ","   diikkikiggkkkkkkkjeeeekkkkd   "," bfdiikkkiigiikkkkkkjeeekkkkkdfb ","   dkkkkkkikkkkikikikeeikkiiid   ","    dkkkkkikkkkkkkkiikjkkiiid    ","  bfdkkkkkkkkkkkkkiiikkkkiiidfb  ","     dkikkkkkkkkkkkkkkkkkiid     ","   bfdiiikkkkkkkkkkkkkkkiiidfb   ","    b ddikkkiikkkkkgggkkidd b    ","     bf ddkiiiikkkgggggdd fb     ","      b f dddiikkkggddd f b      ","        b  f ddddddd f  b        ","           b  f f f  b           ","              b b b              "],
        ["                                 ","              f f f              ","           f ddldldd f           ","        f dddikkkkkkddd f        ","      f ddkkkiikkkkkkkkdd f      ","      ddgkkkkikkkkkkkjekkdd      ","    fdgggkkkkkkkkkkkkeekkiidf    ","     dggkkjkkkkkkkkikkkkkkid     ","   fdkkkkeeekkkkkkkkkkkkkkkkdf   ","    dkkkkeeekkkkkkkkkkkkkkkkd    ","   dkkkkkkekkkkkkkkkkkkkkkkkgd   ","  fdkkkkkkkkkkkikkkkkkkkkkkggdf  ","   dikkkkkkkkkkkkkkkkkkkkkkggd   ","  dkikkkkkikkkkkkkkkkkkkkgggggd  "," fdkkkkkkkkkkkkkkkkkkkkkggggggdf ","  lgkgkkkkkkkkkkkkkkkkkkgggggkl  "," fdgggkkkkkkkkkkkkkkkkkkkkkkgkdf ","  lggkkkkkkkkkkkkkkkkkkkkkkkkil  "," fdkkkkkkkkggkkkkkkkkkejkkkkiidf ","  dkikkkkkkkggkkkkkkkeeekkkkkkd  ","   dkkkkkkkkkkkkkkkkkeeekkkkkd   ","  fdikkkkkikkkkkkkkkkeeekkkkkdf  ","   dkkkkkkikkkkkkkkkkjkkkkkkkd   ","    dkkkkkkkkkkkkkkikkkkkkiid    ","   fdkkkkkkkkkkkkkkkkkkkkkiidf   ","     dkkkkkkkkkkkkkkkkkkkiid     ","    fdkikkkkkkkkkkkkkkkkkiidf    ","      ddikkkkkkkkkkggkkkkdd      ","      f ddkkkikkkkkgggkdd f      ","        f dddkkkkkkgddd f        ","           f ddldldd f           ","              f f f              ","                                 "],
        ["                                 ","              f f f              ","           f ddddddd f           ","        f dddkkkkkkkddd f        ","      f ddkkkkkkkkkkkkkdd f      ","      ddkkkkkkkkkkkkkkkkkdd      ","    fdgkkkkkkkkkkkkkkjekkkidf    ","     dkkkkkkkkkkkkkkkkkkkkkd     ","   fdkkkkjekkkkkkkkkkkkkkkkkdf   ","    dkkkkkekkkkkkkkkkkkkkkkkd    ","   dkkkkkkjkkkkkkkkkkkkkkkkkkd   ","  fdkkkkkkkkkkkkkkkkkkkkkkkkgdf  ","   dkkkkkkkkkkkkokkkkkkkkkkkgd   ","  dkkkkkkkkkkkkodokkkkkkkkkgggd  "," fdkkkkkkkkkkkkdddkkkkkkkkkgggdf ","  dkkkkkkkkkkkkdddkkkkkkkkkkgkd  "," fdkgkkkkkkkkkkdddkkkkkkkkkkkkdf ","  dkgkkkkkkkkkkdddkkkkkkkkkkkkd  "," fdkkkkkkkkkkkkndnkkkkkkkkkkkidf ","  dkkkkkkkkkkkkkdkkkkkejkkkkkkd  ","   dkkkkkkkkkkkknkkkkeeekkkkkd   ","  fdkkkkkkkkkkkkkkkkkkkjkkkkkdf  ","   dkkkkkkkkkkkkkkkkkkkkkkkkkd   ","    dkkkkkkkkkkkkkkkkkkkkkkkd    ","   fdkkkkkkkkkkkkkkkkkkkkkkidf   ","     dkkkkkkkkkkkkkkkkkkkkid     ","    fdkkkkkkkkkkkkkkkkkkkkidf    ","      ddkkkkkkkkkkkkkkkkkdd      ","      f ddkkkkkkkkkkkkkdd f      ","        f dddkkkkkkkddd f        ","           f ddddddd f           ","              f f f              ","                                 "],
        ["                                 ","              b b b              ","           b ccccccc b           ","        b ccckkkkkkkccc b        ","      b cckkkkkkkkkkkkkcc b      ","      cckkkkkkkkkkkkkkkkkcc      ","    bckkkkkkkkkkkkkkkkjkkkkcb    ","     ckkkkkkkkkkkkkkkkkkkkkc     ","   bckkkkkjkkkkkkkkkkkkkkkkkcb   ","    ckkkkkjkkkkkkkkkkkkkkkkkc    ","   ckkkkkkkkkkkkkkkkkkkkkkkkkc   ","  bckkkkkkkkkkkkpkkkkkkkkkkkkcb  ","   ckkkkkkkkkkkpdpkkkkkkkkkkgc   ","  ckkkkkkkkkkkkdddkkkkkkkkkkggc  "," bckkkkkkkkkkkpdddpkkkkkkkkkggcb ","  ckkkkkkkkkkpdddddpkkkkkkkkkkc  "," bckkkkkkkkkkpdddddpkkkkkkkkkkcb ","  ckkkkkkkkkkpdddddpkkkkkkkkkkc  "," bckkkkkkkkkkkdddddkkkkkkkkkkkcb ","  ckkkkkkkkkkkpdddpkkkjkkkkkkkc  ","   ckkkkkkkkkkkdddkkkjjjkkkkkc   ","  bckkkkkkkkkkkpdpkkkkkkkkkkkcb  ","   ckkkkkkkkkkkpdpkkkkkkkkkkkc   ","    ckkkkkkkkkkkpkkkkkkkkkkkc    ","   bckkkkkkkkkkkkkkkkkkkkkkkcb   ","     ckkkkkkkkkkkkkkkkkkkkkc     ","    bckkkkkkkkkkkkkkkkkkkkkcb    ","      cckkkkkkkkkkkkkkkkkcc      ","      b cckkkkkkkkkkkkkcc b      ","        b ccckkkkkkkccc b        ","           b ccccccc b           ","              b b b              ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                r                ","              sddds              ","              ddddd              ","              ddddd              ","              ddddd              ","             rdddddr             ","             ddddddd             ","             ddddddd             ","             ddddddd             ","             qdddddq             ","              ddddd              ","              ddddd              ","              ddddd              ","               ddd               ","               ddd               ","                d                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               rdr               ","              dd dd              ","             rd   dr             ","             d     d             ","            rd     dr            ","           udd     ddu           ","           td       dt           ","            d       d            ","            qd     dq            ","            sd     ds            ","             d     d             ","             d     d             ","             sd   ds             ","              d   d              ","              sd ds              ","               sds               ","                q                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                r                ","               ddd               ","              d   d              ","            vd     dv            ","            vd     dv            ","           cd       dc           ","           xd       dx           ","           wd       dw           ","           cd       dc           ","           cd       dc           ","           vd       dv           ","           vd       dv           ","           vvd     dvv           ","             d     d             ","             dd   dd             ","              d   d              ","              sd ds              ","               qdq               ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               vdv               ","              cdddc              ","             cysssyc             ","            bysssssyb            ","            byBBBBByb            ","            yBBABABBy            ","            yBABBBABy            ","            yBAsssABy            ","            yBA   ABy            ","            yBA   ABy            ","           bysA   Asyb           ","           bysssssssyb           ","           by sssss yb           ","           ccy     ycc           ","            vd     dv            ","            vvd   dvv            ","              d   d              ","               ddd               ","                q                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               bcb               ","               yyy               ","              yG Fy              ","             E     E             ","                                 ","               A A               ","              A   A              ","              A   A              ","            E ABBBA E            ","            E AsssA E            ","            y AsssA y            ","            y  AAA  y            ","            yB  D  By            ","            yBBBBBBBy            ","            bysssssyb            ","            by     yb            ","             cy   yc             ","              cd dc              ","               vdv               ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               EyE               ","                                 ","                                 ","                                 ","               A A               ","              A   A              ","              J   I              ","              A   A              ","              J   I              ","              A m A              ","               AHA               ","            E   G   E            ","            E       E            ","             yG    y             ","             yBBBBBy             ","              ysssy              ","               ysy               ","               byb               ","                c                ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","               AAA               ","              A   A              ","                                 ","              A   A              ","                                 ","              A   A              ","               A A               ","                                 ","                                 ","                                 ","             E     E             ","              y  Fy              ","               y y               ","                y                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","              MMMMM              ","             MMAAAMM             ","             CA   AC             ","              L   K              ","              A   A              ","              L   K              ","              A   A              ","               AxA               ","                                 ","                                 ","                                 ","                                 ","                                 ","               E E               ","                y                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","              EEEEE              ","             EENNNEE             ","             NNNNNNN             ","             NNNNNNN             ","             MA   AM             ","             MA   AM             ","             CA   AC             ","               AAA               ","                                 ","                C                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                c                ","               EEE               ","             EEEEEEE             ","             EENNNEE             ","             NNNNNNN             ","             NNNNNNN             ","              MPPPM              ","                O                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                c                ","                                 ","                                 ","                                 ","                                 ","               EEE               ","              EENEE              ","                N                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                c                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "],
        ["                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                U                ","               TSR               ","                Q                ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 ","                                 "]
        ])
        .keys({
                "b":["minecraft:polished_blackstone_slab[type=bottom]"],
                "c":["minecraft:polished_blackstone_slab[type=double]"],
                "d":["minecraft:spruce_planks"],
                "e":["minecraft:stone"],
                "f":["minecraft:spruce_log[axis=y]"],
                "g":["minecraft:sand"],
                "h":[
                    "minecraft:water",
                    "minecraft:ice"
                ],
                "i":["minecraft:gravel"],
                "j":["minecraft:stone_slab[type=bottom]"],
                "k":[
                    "minecraft:water",
                    "minecraft:ice"
                ],
                "l":[
                    "modular_machinery_reborn:casing_plain",
                    '#modular_machinery_reborn:inputbus',
                    '#modular_machinery_reborn:outputbus',
                    '#modular_machinery_reborn:parallelhatch'
                ],
                "n":["minecraft:spruce_stairs[facing=north+half=top+shape=straight]"],
                "o":["minecraft:spruce_stairs[facing=south+half=top+shape=straight]"],
                "p":["minecraft:spruce_slab[type=top]"],
                "q":["minecraft:spruce_stairs[facing=north+half=top+shape=straight]"],
                "r":["minecraft:spruce_stairs[facing=south+half=top+shape=straight]"],
                "s":["minecraft:spruce_slab[type=top]"],
                "t":["minecraft:quartz_stairs[facing=south+half=bottom+shape=straight]"],
                "u":["minecraft:red_nether_brick_stairs[facing=north+half=bottom+shape=straight]"],
                "v":["minecraft:polished_blackstone_slab[type=top]"],
                "w":["minecraft:red_nether_brick_stairs[facing=south+half=top+shape=straight]"],
                "x":["minecraft:quartz_stairs[facing=north+half=top+shape=straight]"],
                "y":["minecraft:dark_oak_planks"],
                "A":["minecraft:quartz_block"],
                "B":["minecraft:spruce_slab[type=bottom]"],
                "C":["minecraft:lantern[hanging=true]"],
                "D":["minecraft:spruce_slab[type=double]"],
                "E":["minecraft:dark_oak_slab[type=bottom]"],
                "F":["minecraft:barrel"],
                "G":["minecraft:barrel"],
                "H":["minecraft:quartz_stairs[facing=north+half=bottom+shape=straight]"],
                "I":["minecraft:quartz_stairs[facing=west+half=bottom+shape=straight]"],
                "J":["minecraft:quartz_stairs[facing=east+half=bottom+shape=straight]"],
                "K":["minecraft:quartz_stairs[facing=west+half=top+shape=straight]"],
                "L":["minecraft:quartz_stairs[facing=east+half=top+shape=straight]"],
                "M":["minecraft:dark_oak_slab[type=top]"],
                "N":["minecraft:dark_oak_slab[type=double]"],
                "O":["minecraft:chain[axis=y]"],
                "P":["minecraft:dark_oak_stairs[facing=north+half=top+shape=straight]"],
                "Q":["minecraft:spruce_trapdoor[powered=false+open=true+facing=south+half=bottom]"],
                "R":["minecraft:spruce_trapdoor[powered=false+open=true+facing=east+half=bottom]"],
                "S":["minecraft:campfire"],
                "T":["minecraft:spruce_trapdoor[powered=false+open=true+facing=west+half=bottom]"],
                "U":["minecraft:spruce_trapdoor[powered=false+open=true+facing=north+half=bottom]"]
            })
        )
});
//design by BitGardener https://www.youtube.com/watch?v=rXV_b7J1TB4