/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
MMREvents.machines(catalyst => {
    catalyst.create("mmr:celestial_forge")
        .color('#FF6fff00')
        .name(Component.translatable("catalyst.mmr.machine.celestial_forge"))
        .structure(
            MMRStructureBuilder.create()
                .pattern([
                    [
                        "KKKKKKKKzCzKKKKKKKK",
                        "KLLLLLLLvvvLLLLLLLK",
                        "KLwwwwwLvbvLuuuuuLK",
                        "KLwykywLvvvLuxkxuLK",
                        "KLwkBkwLvvvLukAkuLK",
                        "KLwykywLvbvLuxkxuLK",
                        "KLwwwwwLvvvLuuuuuLK",
                        "KLLLLLLpppppLLLLLLK",
                        "zrrrrrrpkkkpqqqqqqz",
                        "trbrrbrpkkkpqbqqbqs",
                        "zrrrrrrpkkkpqqqqqqz",
                        "KLLLLLLpppppLLLLLLK",
                        "KLiiiiiLQQQLSSSSSLK",
                        "KLilkliLQbQLSjkjSLK",
                        "KLikokiLQQQLSknkSLK",
                        "KLilkliLQQQLSjkjSLK",
                        "KLiiiiiLQbQLSSSSSLK",
                        "KLLLLLLLQQQLLLLLLLK",
                        "KKKKKKKKzIzKKKKKKKK"
                    ],
                    [
                        "DE               ED",
                        "E                 E",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "         k         ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "E                 E",
                        "DE               ED"
                    ],
                    [
                        "D                 D",
                        "                   ",
                        "                   ",
                        "                   ",
                        "              FF   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "         m         ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "D                 D"
                    ],
                    [
                        "D                 D",
                        "                   ",
                        "   HHN        FF   ",
                        "   HHHH      FFFF  ",
                        "   MHHH      FFFFF ",
                        "   HHHH      FFFF  ",
                        "   HHHJ       FF   ",
                        "     H             ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "              G    ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "D                 D"
                    ],
                    [
                        "                   ",
                        "    H              ",
                        "   HNN         FF  ",
                        "   HHH       FFFFF ",
                        "   MHHH     FFFFFF ",
                        "   MHHJ       FFFF ",
                        "   MMJ        PFF  ",
                        "   HMH             ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "             GOO   ",
                        "            GG G   ",
                        "            GGGG   ",
                        "              G    ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "    V              ",
                        "                   ",
                        "    X          W   ",
                        "                   ",
                        "    V              ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "             GG    ",
                        "            GGGO   ",
                        "    Uf     GRRRGG  ",
                        "           GRG G   ",
                        "            GGGR   ",
                        "              G    ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "    V              ",
                        "                   ",
                        "    X          W   ",
                        "                   ",
                        "    V              ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "    f              ",
                        "   fUf             ",
                        "  fUUf             ",
                        "   UUU        R    ",
                        "             RRR   ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "    V              ",
                        "              aaa  ",
                        "    X         aWa  ",
                        "                   ",
                        "    V          `   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "   UUUU            ",
                        "  _UUUU            ",
                        "  _UUUU            ",
                        "  UUUUU            ",
                        "  UUUf        R    ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "    V              ",
                        "                   ",
                        "    X         aaa  ",
                        "              aWa  ",
                        "    V         aWa  ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "  __UU             ",
                        "  _UeUU            ",
                        "  _eeeU            ",
                        "  UeeeU            ",
                        "  UeeeU       d    ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "    H              ",
                        "    H              ",
                        "    H              ",
                        "    H              ",
                        "    H         aWa  ",
                        "    H              ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "  gf f             ",
                        "                   ",
                        "   f f             ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "   f f             ",
                        "                   ",
                        "   f f             ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "   f f             ",
                        "                   ",
                        "   f f             ",
                        "                   ",
                        "                   ",
                        "                   "
                    ],
                    [
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "                   ",
                        "    hh             ",
                        "    eh             ",
                        "   f h             ",
                        "                   ",
                        "                   ",
                        "                   "
                    ]
                ])
                .keys({
                    "a": ["minecraft:flowering_azalea_leaves"],
                    "b": ['chipped:fancy_redstone_lamp'],
                    "d": ["minecraft:end_rod[facing=up]"],
                    "e": ["minecraft:nether_bricks"],
                    "f": ["minecraft:nether_brick_wall"],
                    "g": ["minecraft:soul_lantern"],
                    "h": ["minecraft:nether_brick_slab[type=bottom]"],
                    "i": ["eternalores:uraninite_block"],
                    "j": ["modular_machinery_reborn:casing_vent"],
                    "k": ["modular_machinery_reborn:casing_plain"],
                    "l": ["modular_machinery_reborn:casing_gearbox"],
                    "n": ["#modular_machinery_reborn:energyhatch"],
                    "o": ["#modular_machinery_reborn:fluidhatch"],
                    "p": ["chipped:smooth_blackstone_column"],
                    "q": ["rechiseled:nether_bricks_brick_pattern_connecting"],
                    "r": ["ae2:smooth_quartz_block"],
                    "s": ["#modular_machinery_reborn:fluidhatch"],
                    "t": ["#modular_machinery_reborn:itembus"],
                    "u": ["create:weathered_iron_block"],
                    "v": ["rechiseled:end_stone_brick_pattern_connecting"],
                    "w": ["minecraft:sculk_catalyst"],
                    "x": ["modular_machinery_reborn:casing_firebox"],
                    "y": ["modular_machinery_reborn:casing_circuitry"],
                    "z": ['modular_machinery_reborn:casing_reinforced'],
                    "A": ["modular_machinery_reborn:dimensional_detector"],
                    "B": ["#modular_machinery_reborn:itembus"],
                    "C": [
                        "#modular_machinery_reborn:parallelhatch",
                        'minecraft:polished_blackstone_bricks'
                    ],
                    "D": ["chipped:fine_coal_block_pillar"],
                    "E": ["chipped:tiny_layered_coal_block_slabs"],
                    "F": [
                        "minecraft:dirt",
                        "minecraft:grass_block"
                    ],
                    "G": ["minecraft:end_stone"],
                    "H": ["minecraft:deepslate"],
                    "I": ['#modular_machinery_reborn:energyhatch'],
                    "J": ["minecraft:deepslate_diamond_ore"],
                    "K": [
                        'minecraft:polished_blackstone_bricks',
                        '#modular_machinery_reborn:itembus',
                        '#modular_machinery_reborn:fluidhatch',
                        '#modular_machinery_reborn:energyhatch'
                    ],
                    "L": ['rechiseled:quartz_block_connecting_connecting'],
                    "M": ["minecraft:sculk"],
                    "N": ["minecraft:deepslate_redstone_ore"],
                    "O": ["minecraft:end_stone_bricks"],
                    "P": ["minecraft:heavy_core"],
                    "Q": ['rechiseled:stone_brick_pattern_connecting'],
                    "R": ["minecraft:purpur_block"],
                    "S": ['eternalores:shadowsteel_block'],
                    "U": ["minecraft:netherrack"],
                    "V": ["rechiseled:cobbled_deepslate_pillar_connecting[axis=y]"],
                    "W": ["minecraft:oak_log"],
                    "X": ["minecraft:reinforced_deepslate"],
                    "_": ["minecraft:soul_soil"],
                    "`": ["minecraft:lantern"]
                })
        )
        
    
})
/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/